### ISSUE TITLE
Cloud9: Error handling

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/cpp-tutorial#10]
C9 runs the last working version when there is an error in the current code.
Is it possible to disable this behaviour?
(Relates to #9 )

**Comment by RagnarGrootKoerkamp** [comment]
@manonverra:
I know a fix for this issue:
First run a file ('test.cpp'). Then, in the top right corner of the run-window, select runner-> edit runner. Then, change the `;` in the line after `g++` to ` && `, so that the executable isn't run when building the file fails. Save this new file as `cpp-runner.run`. Next select this runner in the Runner popup-menu.

**Comment by RagnarGrootKoerkamp** [comment]
Ok, so it might be a bit more complicated to make all changes persistent. It would be ideal when we could let people clone our own C9 project, so all settings are set immediately.

**Comment by manonverra** [comment]
Your solution works, but trial-and-error taught me that you have to replace both semicolons in that line (maybe that's what you meant to say and I misunderstood). 

C9 remembers to use that runner for a specific file, so they would only have to set it once. However, this new runner is not yet set as the default runner for new files. You can do that adding a new config in the run configurations.

I'm not sure if this is best solution for the course though. I do not like cloning since if people want to continue programming after the course using C9 they would still have to clone the settings for a new workspace, not knowing what they're changing. But setting them up manually in the course takes too much time. Might be easier to just use the terminal and avoid the problem.

**Comment by RagnarGrootKoerkamp** [comment]
In the current version, this bug seems to be fixed
